# Gradle Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.3:v2
loader_version=0.16.13

# Mod Properties
maven_group=me.caseload
archives_base_name=knockbacksync

# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.140.0+1.21.11

githubRepo=CASELOAD7000/knockback-sync