name: KbSync
version: '${project.version}'
author: caseload
description: Synchronizes player knockback for smoother gameplay. Requires ProtocolLib.
main: me.caseload.kbsync.KbSync
api-version: 1.21
depend: [ProtocolLib]

commands:
  knockbacksync:
    aliases: [kbsync, kbscaling, kbscale, knockbackscaling, knockbackscale]

permissions:
  kbsync.admin:
    default: op